# Generated by Django 4.2.25 on 2025-10-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='players.category'),
        ),
        migrations.RenameField(
            model_name='player',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='player',
            name='owner',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='acudiente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
