# Generated by Django 4.2.25 on 2025-11-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_uniformej_split_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformej',
            name='player',
        ),
        migrations.RemoveField(
            model_name='uniformep',
            name='player',
        ),
        migrations.DeleteModel(
            name='UniformeBSP',
        ),
        migrations.DeleteModel(
            name='UniformeJ',
        ),
        migrations.DeleteModel(
            name='UniformeP',
        ),
    ]
