# Generated by Django 4.2.25 on 2025-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_make_normalized_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
