# Generated by Django 4.2.26 on 2025-11-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_acudiente_id_alter_category_id_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
